POST http://localhost:4000/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoic3VzbGFAbWFpbC5jb20iLCJpYXQiOjE3NzM3NTc1NDgsImV4cCI6MTc3Mzc2MTE0OCwiYXVkIjoibG9jYWxob3N0OjQwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NDAwMCJ9.3lvkk6VFmUtX3LXnTqF06L7_jm7nuQrusOQSpqWCuEI


{
    "name": "JavaScript21",
    "slug": "javascript2121",
    "description":" All posts java scripts"
}