POST http://localhost:4000/users/
Content-Type: application/json


{

    "firstName":"Maks",
    "lastName":"Susla",
    "email":"susla@mail.com",
    "password":"Qwerty123!"
}


POST http://localhost:4000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoic3VzbGFAbWFpbC5jb20iLCJpYXQiOjE3NzM3NDcxMTMsImV4cCI6MTc3Mzc1MDcxMywiYXVkIjoibG9jYWxob3N0OjQwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NDAwMCJ9.QFAHjQCHoTcipt5ad58AGQl4xgmdN8h7lVmzu-E6deg
{
    "users":[
{

    "firstName":"Jone1",
    "lastName":"doe2",
    "email":"Joneeee@email.com",
    "password":"Qwerty12311!"
},
{

    "firstName":"Jone2",
    "lastName":"doe2",
    "email":"Marke@email.com",
    "password":"Qwerty123!11"
}
]
}