POST http://localhost:4000/auth/refresh-tokens
Content-type: application/json
Authorization: Berear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoic3VzbGFAbWFpbC5jb20iLCJpYXQiOjE3NzQwMDUxNzMsImV4cCI6MTc3NDAwODc3MywiYXVkIjoibG9jYWxob3N0OjQwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NDAwMCJ9.ra2Nh7M36k4RRsivXdwPTQ7F7Zea48kRnOZffRF7rjw

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTc3NDAwNTE3MywiZXhwIjoxNzc0MDkxNTczLCJhdWQiOiJsb2NhbGhvc3Q6NDAwMCIsImlzcyI6ImxvY2FsaG9zdDo0MDAwIn0.c0tiBhRy6WsXCKt3_XQkzkTd_Ts9vK9uMVXq7MJiQjo"
}